### ISSUE TITLE
ArgumentException when running build.cmd

### ISSUE THREAD

**Issue by Slesa** [fsprojects/ProjectScaffold#110]
Running for the first time in this directory, build.cmd reports 'build process successful, 0 errors, 0 warnings' Starting target RunTests.
...
D:\dev\github\Poseidon.new\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "D:\dev\github\Poseidon.new\tests\Poseidon.Tests\bin\Release\Poseidon.Tests.dll" "-xml:TestResults.xml"
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Unhandled Exception:
System.ArgumentException: Das Element wurde bereits hinzugefügt. Schlüssel im Wörterbuch: "tmp". Hinzuzufügender Schlüssel: "tmp".

(key 'tmp' already added to dictionary)

Maybe to mention: I started build.cmd under a cygwin bash shell.

**Comment by dsyme** [comment]
Very old issue, please reopen if it is still a problem
