### ISSUE TITLE
Scaffold for Type Providers

### ISSUE THREAD

**Issue by rojepp** [fsprojects/ProjectScaffold#112]
It would be great to shorten the distance from having an idea for a type provider to spiking it.
Some changes to ProjectScaffold would be:
- Two test solutions, one for implementation and another for testing the TP. 
- The implementation solution has debug action set to start the Test solution.
- The implementation solution would probably still have its own test project, for regular, non-TP unit tests.
- A starter TP would be included with basic TP stuff, and tests for the TP

So you do your work in the implementation solution and 
Other changes? 

Perhaps this could be done in a separate branch, so that changes to ProjectScaffold can be merged without too much work?

**Comment by dsyme** [comment]
Closing old issue - please start a new scaffolding project if you'd like this
