### ISSUE TITLE
Create Visual Studio template

### ISSUE THREAD

**Issue by haf** [fsprojects/ProjectScaffold#13]
It would be great if you'd create a Visual Studio template for this so that I can choose the 'good' F# project file (fsproj) when I create a new F# project instead of having to hack it manually.

Also, I haven't found a blog entry or other documentation describing the changes to the default fsproj nor how they relate to compiling this on mono and windows: do you have any suggestions on where to look?

**Comment by dsyme** [comment]
@pblasucci Given the high number of bugs in this repo I'm going to start a cleanout to get it down, and perhaps to simplify the scaffold as well.  I'll start by closing out long-ago suggestions and enhancements like this one, thanks

**Comment by pblasucci** [comment]
@dsyme Thanks! I think this is a great time for a little "house keeping" 👍
