### ISSUE TITLE
Fresh clone + run build.cmd fails

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/ProjectScaffold#140]
Locked version resolutions written to C:\Git\FSharp.ProjectScaffold\paket.lock
    Downloading fsharp/FAKE:412ed0da4a9a8635e243e2ea06cf654ca805f6d8 modules/Octokit/Octokit.fsx to C:\Git\FSharp.ProjectScaffold\paket-files\fsharp\FAKE\modules\Octokit\Octokit.fsx
    Paket failed with:
            Could not find file 'C:\Git\FSharp.ProjectScaffold\paket-files\fsharp\FAKE\modules\Octokit\paket.version'.

    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FakeLib, Version=3.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
       at <StartupCode$FAKE>.$Program.main@()

    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FakeLib, Version=3.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
       at <StartupCode$FAKE>.$Program.main@()

    C:\Git\FSharp.ProjectScaffold>

**Comment by cdrnet** [comment]
Yes, I noticed this as well when looking at fsprojects/Paket#600, seems to be related.
