### ISSUE TITLE
Depend on FSharp.Core nuget?

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/ProjectScaffold#163]
Apparently it is best practice to reference F# Nuget package instead of depending on the one in the GAC.

Maybe ProjectScaffold can generate this right away? Adding FSharp.Core to paket.dependencies and paket.references

https://github.com/fsharp/fsharp/issues/352

**Comment by forki** [comment]
Please read @dsyme's guide on referencing the fsharp.core. http://fsharp.github.io/2015/04/18/fsharp-core-notes.html referencing the nuget package is not the best solution in every situation. We should discuss a way to bake the guide into projectscaffold as best as we can.

**Comment by CumpsD** [comment]
Thanks, didn't knew that, thought I overheard you say always reference the nuget :)

**Comment by forki** [comment]
Yes I did. That's probably one of the reasons why @dsyme wrote this very detailed guide ;-)

**Comment by dsyme** [comment]
I don't actually see many technical problems with referencing the current nuget packages, But ideally the VS and XS templates would be updated for consistency.

**Comment by dsyme** [comment]
If you like send a PR with updated guidance to that guide, and we can discuss on that PR thread.

**Comment by forki** [comment]
Yes I was thinking about this. But I have to reread, rethink and test some
things before I do this. But I think the discussion will be much easier
now, since the new guide has already so many things covered.

**Comment by dsyme** [comment]
I've been thinking. It does seems pretty reasonable for the scaffold to rely on the nuget package at this stage, though it may cause some pain, either for consumers or later if the package changes in some way.

**Comment by dsyme** [comment]
I've starterd a discussion thread about this here: https://github.com/fsharp/fsharp.github.io/issues/26

**Comment by dsyme** [comment]
This is now being done
