### ISSUE TITLE
repo.Revision is deprecated.

### ISSUE THREAD

**Issue by halcwb** [fsprojects/ProjectScaffold#166]
In the 'SourceLink' target the following is deprecated:

    proj.CreateSrcSrv baseUrl repo.Revision (repo.Paths files)

the suggestion is that is should be: repo.Commit

**Comment by forki** [comment]
Please send a pull request. Thanks

**Comment by halcwb** [comment]
I think I made a [pull request] (https://github.com/fsprojects/ProjectScaffold/pull/167)?

**Comment by gsvgit** [comment]
Seems that could be closed.
