### ISSUE TITLE
StackOverflowException when generating reference documentation

### ISSUE THREAD

**Issue by Rickasaurus** [fsprojects/ProjectScaffold#170]
This is really strange - it's happening on our build server but not when we build locally:

> Process is terminated due to StackOverflowException.
> Running build failed.
> 
> Error:
> System.Exception: generating reference documentation failed
> at FSI_0001.Build.clo@194-19.Invoke(Unit _arg3) in C:\Builds\14\FSharp.ToolBelt\FSharp.ToolBelt  Nuget Release\src\build.fsx:line 196
> at Fake.TargetHelper.runTarget@329(String targetName) in  C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 343
> Status:        Failure

**Comment by tpetricek** [comment]
Can you share what is in `build.fsx` on line 196?

If this is invoking F# Formatting to generate XML documentation, then I think we might have seen this error before (cc @matthid). But the best choice would be to update to the latest F# Formatting, where a lot of things have been significantly improved (thanks to @matthid's great work :-))

**Comment by Rickasaurus** [comment]
Sure, 196 is the second line of:
```fsharp
Target "GenerateReferenceDocs" (fun _ ->
    if not <| executeFSIWithArgs "docs/tools" "generate.fsx" ["--define:RELEASE"; "--define:REFERENCE"] [] then
      failwith "generating reference documentation failed"
)
```

**Comment by Rickasaurus** [comment]
What's the best way to update? Just pull the latest docs/tools from the scaffold git?

**Comment by matthid** [comment]
It's hard to tell without the stack trace of the overflow, however most of the time when this happens it is related to FSharp.Compiler.Service getting an invalid FSharp.Core.dll and FSharp.Core.(optdata/sigdata) combination.

To further track this down:
Is your build setup to emit a FSharp.Core.dll in the output directory? Can you try emitting FSharp.Core.sigdata and FSharp.Core.optdata as well or try removing any FSharp.Core related files?
Is FSharp actually installed on the build server?
What OS is your build server using?
FSharp.Formatting version? Mono version? F# version?
Can you try to get the underlying stack trace. For example by running the fsi directly with
```
cd docs/tools && mono --debug fsi.exe generate.fsx --define:RELEASE --define:REFERENCE
```

Further information: http://fsharp.github.io/FSharp.Compiler.Service/corelib.html
and http://fsharp.github.io/2015/04/18/fsharp-core-notes.html

**Comment by davidpodhola** [comment]
I am experiencing the same behavior. What is strange is, that running `fsi.exe generate.fsx --define:RELEASE --define:REFERENCE` works
![generate](https://cloud.githubusercontent.com/assets/436605/8030943/41a51346-0dcb-11e5-9307-cf6619dd7117.PNG)

but running `build GenerateReferenceDocs` not
![generatereferencedocs](https://cloud.githubusercontent.com/assets/436605/8030981/6d6215a6-0dcb-11e5-8e88-973bdbd578e5.PNG)

To answer the other questions:
Is your build setup to emit a FSharp.Core.dll in the output directory? YES, 4.3.1 Can you try emitting FSharp.Core.sigdata and FSharp.Core.optdata as well or try removing any FSharp.Core related files?
Is FSharp actually installed on the build server? YES, this is from my dev machine
What OS is your build server using? Windows 8.1
FSharp.Formatting version? FSharp.Formatting.2.9.6.nupkg (upgrading to the latest version from github did not help)
Mono version? No Mono, .NET
F# version? 4.3.1

**Comment by troykershaw** [comment]
I had this same problem. What solved it for me was to remove references to FSharp.Core from the offending projects and re add it. Works like a dream now!

**Comment by larsw** [comment]
I'm experiencing the same problem; @troykershaw by removing and re-adding FSharp.Core; did you manually edit the .fsproj files? AFAIK it is not possible to remove the FSharp.Core reference from the References folder in the project  (in Visual Studio).

**Comment by dsyme** [comment]
This was fixed way back
