### ISSUE TITLE
Project structure: nuget

### ISSUE THREAD

**Issue by koenmetsu** [fsprojects/ProjectScaffold#183]
The [project structure documentation](https://fsprojects.github.io/ProjectScaffold/structure.html) mentions a folder "nuget", which has a dead link to https://github.com/fsprojects/ProjectScaffold/tree/master/nuget.

Is there a new place for nuget related files?

**Comment by jackfoxy** [comment]
project structure page needs updating https://github.com/fsprojects/ProjectScaffold/issues/317
closing this issue to consolidate
