### ISSUE TITLE
Build on AppVeyor fails -- missing `FSharp.Core`

### ISSUE THREAD

**Issue by sideeffffect** [fsprojects/ProjectScaffold#193]
I use a project created from `ProjectScaffold`.
Building on Travis works OK, but building on AppVeyor fails with the following error:

```
1) System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

[full log on AppVeyor](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.5)

what am I doing wrong? builds of [`ProjectScaffold` itself](https://ci.appveyor.com/project/fsgit/projectscaffold) seem to be doing OK.

**Comment by rneatherway** [comment]
Does your appveyor config use VS2013 or VS2015?

**Comment by sergey-tihon** [comment]
According to build log `FSharpLint` could not find `FSharp.Core`.
It is not directly related to `ProjectScaffold` because we have no dependency to `FSharpLint` now.

//cc @duckmatt

**Comment by duckmatt** [comment]
@sergey-tihon is correct, that's coming from `FSharpLint` not anything in this project, try upgrading to at least `0.2.5` to fix

**Comment by sergey-tihon** [comment]
As I understand @sideeffffect uses FSharpLint (0.2.6) https://github.com/sideeffffect/FSharpHello/blob/master/paket.lock#L16

**Comment by duckmatt** [comment]
The [linked build](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.5) is 21 days old, fingers crossed it would work now on the current master

    FSharpLint 0.2.3 unzipped to C:\projects\fsharphello\packages\FSharpLint

**Comment by sideeffffect** [comment]
how can I try building on AppVeyor with FSharpLint from master?

**Comment by duckmatt** [comment]
Sorry I meant building the master branch of your project with FSharpLint >=0.2.5. From your latest builds on app veyor that seems to be the case as it's running as expected:

    Successfully linted C:\projects\fsharphello\tests\FSharpHello.Tests\FSharpHello.Tests.fsproj. Linted 1 files and found 1 warnings.

But the build is now failed by a broken test `FSharpHello.Tests.hello`: https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.8

**Comment by sideeffffect** [comment]
good, the 'missing `FSharp.Core`' error seems to be gone. now it fails with [the following message](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.8#L189).
I have no idea what's going wrong. should I create a new issue for this?

```
Errors and Failures:
1) Test Error : FSharpHello.Tests.hello returns 42
   System.MissingMethodException : Method not found: 'Void FsUnit.TopLevelOperators.should(Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!1>, !!0, System.Object)'.
   at FSharpHello.Tests.hello returns 42()
 
 
Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed (1).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
   at FSI_0001.Build.clo@137-11.Invoke(Unit _arg7) in C:\projects\fsharphello\build.fsx:line 138
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411
```

**Comment by rneatherway** [comment]
This is an issue with FsUnit: https://github.com/fsprojects/FsUnit/issues/23

**Comment by sideeffffect** [comment]
this is fixed
