### ISSUE TITLE
Is Scaffold able to produce multiple nuget packages ?

### ISSUE THREAD

**Issue by theor** [fsprojects/ProjectScaffold#196]
I'd like to keep one solution for several projects, each one producing a nuget package (think of Rx-Main, Rx-WPF, ...). How would you do that with scaffold ?

Thanks,

Théo

**Comment by sergey-tihon** [comment]
Just put `paket.template` near each project file
Example is here https://github.com/fsprojects/FsUnit

**Comment by theor** [comment]
...it's obvious now. I guess I misread the paket doc. Thanks a lot!

**Comment by sergey-tihon** [comment]
The most important thing about `paket.template` to realize it that there are two types of tempaltes:
- project - when Paket tries to infer all information from your project file
- file - when you have manual control over all nuget package properties.

**Comment by theor** [comment]
Thanks a lot !
