### ISSUE TITLE
Internal knowledge about release steps required.

### ISSUE THREAD

**Issue by gsvgit** [fsprojects/ProjectScaffold#199]
Hi

Does any information about Scaffold working process exist? I have a problem with release and seems that I do not understand all steps of Scaffold. For example, I have the next error:
```
Finished Target: ReleaseDocs
Starting Target: NuGet (==> All)
C:\gsv\projects\YC\YC.PrettyPrinter\.paket\paket.exe pack output bin version  0.0.1-beta releaseNotes  "Initial release"
Paket failed with:
        Could not find a part of the path 'C:\gsv\projects\YC\YC.PrettyPrinter\temp\gh-pages\src\YC.PrettyPrinter\bin\Release\YC.PrettyPrinter.dll'.
Running build failed.
```

Whether packaging really should be performed on gh-pages branch? (why binaries should be in temp\gh-pages\src\ ?) If so, then compilation step is missed. If no, then switching back to master does not perform correctly.

**Comment by gsvgit** [comment]
Seems that I have problems because my gh-pages branch is not clear. It was branched from master and contains src folder. So, packet.template also exists here and Packed try to process it while process all subfolders recursively. May be short note about gh-pages branch should by included to  Scaffold getting started manual? Just to remind user of necessity to clean  directories in gh-pages.

**Comment by forki** [comment]
Yes. Or even better: try to automate things in the init script

**Comment by gsvgit** [comment]
Issue #201 created. Seems, that this issue can be closed.
