### ISSUE TITLE
Automate gh-pages branch createon

### ISSUE THREAD

**Issue by gsvgit** [fsprojects/ProjectScaffold#201]
It would be useful to automate gh-pages branch creation in init script.
Note that Scaffold can be used for projects with long history, so
- gh-pages may exist and contain important data. But in this case it can contain some files (e.g paket.template) which could break package creation process (look at issue #199). So, existing branch should be checked and cleaned if possible.
- gh-pages may not exists, but it can not be created by simple branching (look at the previous point). What is the right way: 
  - branch from initial commit 
  - branch from current state and cleanup ?

**Comment by klettier** [comment]
- Option 1 

Create an **orphan** branch with [git](http://stackoverflow.com/a/4288660)
```
git checkout --orphan gh-pages
git rm -rf .
git commit -m 'Initial commit'
```
- Option 2

Create  gh-pages branch from GitHub
Settings -> options -> GitHub Pages -> Lauch automatic page generator

**Comment by gsvgit** [comment]
@klettier Thanks, but seems it is for manual creation (especially second option). What about automation?

**Comment by klettier** [comment]
It could be easy to apply first option in build script if the branch doesn't exist. 
I'm not a fan of implicit stuff like creation of the branch without asking the end user, what are your thoughts? 

klettier

**Comment by gsvgit** [comment]
I think you are right that implicit branch creation is not good idea but scaffold initial script is interactive. So, user can choose necessary options (like repo initialisation in current version).

**Comment by klettier** [comment]
For me when we init the repo (wantGit = true)  we should init this branch too (implicit way). 
If we are working on a legacy repo we can propose 
- Branch creation on init (Check state first) 
- Maybe a specific target ?

**Comment by gsvgit** [comment]
Sounds great.
Seems that on a legacy repo we should use explicit way. Thus separated step "Init gh-pages branch? [Y|n]" should be in scaffold initialization script (with state checking of course).

**Comment by jackfoxy** [comment]
Github pages now supports the master branch docs folder as source https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ 
This would be a somewhat breaking change, but I'm not sure it matters. (Who ever merges ProjectScaffold changes once they have cloned it?)

Much simpler for people to implement and understand.

**Comment by forki** [comment]
Cool we could use that for new projects. Usually people don't merge projectscaffold back to existing projects

**Comment by jackfoxy** [comment]
I have a PR related to implement the new model of publising docs. https://github.com/fsprojects/ProjectScaffold/pull/278 If there is interest in carrying this forward, I can resolve the merge conflict. This is implemented as a hard cut-over to the simpler model of publishing docs on Github. In other words the gh-pages option would not be available.

**Comment by jackfoxy** [comment]
Closing this in favor of keeping discussion open in this issue https://github.com/fsprojects/ProjectScaffold/issues/304
