### ISSUE TITLE
Is it possible to create multi-dll package?

### ISSUE THREAD

**Issue by gsvgit** [fsprojects/ProjectScaffold#204]
Is it possible to create multi-dll package for multi project solution with Scaffold? Seems that current script allow to use "package per project" way only. Seems that script  try to find template file for each project in src folder. Isn't it?

Thanks.

**Comment by sergey-tihon** [comment]
No, build script process all `*paket.template` files in all project folders.
Here is example of generating 2 nuget packages per project
https://github.com/sergey-tihon/FsUnit/tree/master/src/FsUnit.Xunit
