### ISSUE TITLE
Proposal: Replace .sln with msbuild .proj

### ISSUE THREAD

**Issue by t3476** [fsprojects/ProjectScaffold#208]
Here is a stackoverflow question: [Replace .sln with MSBuild and wrap contained projects into targets](http://stackoverflow.com/questions/2472183/replace-sln-with-msbuild-and-wrap-contained-projects-into-targets).
The answer illustrated a msbuild replacement which looks better than what's in .sln. The Contents of .sln looks illogical and verbose.

**Comment by gsvgit** [comment]
I think that only as option. ProjectScaffold very useful for beginners and .sln is default format when you use MS VS for development. So, sln format support should be default.
