### ISSUE TITLE
mozroots no longer required for Mono 3.12+

### ISSUE THREAD

**Issue by robwestwood** [fsprojects/ProjectScaffold#213]
Since Mono version 3.12, it is no longer necessary to use the mozroots utility. Upon installation (for packaged mono) cert-sync is run to synchronise OS certificates to the Mono certificate store.

Details: [cert-sync change in Mono 3.12](http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync).

**Comment by knocte** [comment]
AFAIU, this change is in Mono, but it's up to distros to pick it up in their Mono packaging. Debian/Ubuntu did, and e.g. with Ubuntu16.04 you can use MonoDevelop+Nuget out of the box.

**Comment by robwestwood** [comment]
Thanks, @knocte.

Looking at patch #236 this covers all bases as far as I can understand, so I'm marking this issue as closed.
