### ISSUE TITLE
Adding additional projects?

### ISSUE THREAD

**Issue by elliottt** [fsprojects/ProjectScaffold#214]
I'm new to msbuild and project organization with .NET projects, so please excuse what feels like a simple question :)

Once I've used the project scaffold to initialize my project, what's the best way to add additional projects under the src/ directory? Ultimately, I would like to be able to do F# development without the aid of an IDE, as I'm more comfortable in a unix environment, but it doesn't seem like the project scaffold bootstrapping scripts help with this. Should I just use something like monodevelop to manipulate the top-level .sln file and src/ directory contents, while doing the majority of my development in vim?

**Comment by wewebber** [comment]
Bump

**Comment by wewebber** [comment]
Answering my own bump.  I used Forge:

    http://fsprojects.github.io/Forge/index.html

to create the project folder itself, but still had to edit the .sln file to add the project to the solution (which is slightly non-obvious how to do).

**Comment by elliottt** [comment]
I was hoping that there would be an easier way to manipulate the sln file programmatically, but maybe using an IDE is the best option right now.

**Comment by elliottt** [comment]
I'll take a look at forge, thanks for the pointer.
