### ISSUE TITLE
Type provider from FSharp.Data crashes Fake

### ISSUE THREAD

**Issue by quant1729** [fsprojects/ProjectScaffold#232]
Hello, 

Today I started using project scaffold and immediately faced this issue. If I add to my code some reference to JsonProvider from FSharp.Data, I immediately get build crashing with error:

Binding session to 'D:\Username\Documents\Visual Studio 2015\Projects\A\pac
kages\build\FSharp.Formatting\lib/net40\FSharp.MetadataFormat.dll'...
Binding session to 'D:\Username\Documents\Visual Studio 2015\Projects\A\pac
kages\build\FSharp.Formatting\lib/net40\RazorEngine.dll'...

error FS0193: The module/namespace 'FSharp.Data' from compilation unit 'FSharp.D
ata' did not contain the namespace, module or type 'JsonProvider,Sample="data/file.json"'

error FS0193: The module/namespace 'FSharp.Data' from compilation unit 'FSharp.D
ata' did not contain the namespace, module or type 'JsonProvider,Sample="data/file2.json"'
Stopped due to error

Running build failed.
Error:
System.Exception: generating reference documentation failed
   at FSI_0001.Build.buildDocumentationTarget(String fsiargs, String target)
   at FSI_0001.Build.clo@225-19.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 483

Please advise.

Best regards,
Pavel.

**Comment by arcturius** [comment]
Hello?

**Comment by sergey-tihon** [comment]
Please try to use full path to the JSON files "data/file.json"

**Comment by arcturius** [comment]
Thank you. will try it. Reporting one more issue in a separate ticket.

**Comment by dsyme** [comment]
This is a FAKE or FSharp.Data issue, not a scaffolding issue
