### ISSUE TITLE
Using events in interop crashes Fake

### ISSUE THREAD

**Issue by quant1729** [fsprojects/ProjectScaffold#234]
Hello, 

I am using interop to work with 3rd party software. My C# code crashed Fake on my PC once I added 3rd party libs to the project: 

unknown(1,1): error FS1091: The event 'OnRemove' has a non-standard type. If thi
s event is declared in another CLI language, you may need to access this event u
sing the explicit add_OnRemove and remove_OnRemove methods for the event. If thi
s event is declared in F#, make the type of the event an instantiation of either
 'IDelegateEvent<_>' or 'IEvent<_,_>'.

... (skipped many other events with signatures from 3rd party lib)....

Stopped due to error

Running build failed.
Error:
System.Exception: generating reference documentation failed
   at FSI_0001.Build.buildDocumentationTarget(String fsiargs, String target)
   at FSI_0001.Build.clo@225-19.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 483

My code is not F#. I subscribe to them in a standard way in C# (+=). 

Please advise.

Regards,
Pavel.

**Comment by arcturius** [comment]
One more thing. Looked into docs. I could't find a way to exclude particular projects/files from this fragile build step. How can I do this?

**Comment by Vidarls** [comment]
known issue with fsharp.formatting. (or actually the Fcs powering fsharp.formatting) Can't remember issue numbers, and too lazy to look up on the phone.
To exclude anything from generating docs, you need to modify the docs/tools/generate.fsx. There is a function for getting convention based files to include. Or alternatively, disable the conventions and use the manual option at the top of the file.

**Comment by dsyme** [comment]
This is a question about FAKE
