### ISSUE TITLE
GenerateReferenceDocs target failing

### ISSUE THREAD

**Issue by johnazariah** [fsprojects/ProjectScaffold#237]
My build has been failing for the last 9 days on the GenerateReferenceDocs target. All preceding targets are working correctly.

[projectscaffold-generatereferencedocs-crash.txt](https://github.com/fsprojects/ProjectScaffold/files/119440/projectscaffold-generatereferencedocs-crash.txt)

I have run paket update, and these are the versions I have:

Paket version 2.49.5.0
Resolving packages for group Main:
 - Octokit 0.18.0
 - NUnit 2.6.4
 - NUnit.Runners 2.6.4
 - Azure.Batch 3.0.0
 - FAKE 4.19.0
 - FSharp.Data 2.2.5
 - FSharp.Formatting 2.14.0
 - FSharpx.Core 1.8.41
 - FsUnit 1.4.1.0
 - newtonsoft.json 8.0.2
 - SourceLink.Fake 1.1.0
 - Microsoft.Net.Http 2.2.29
 - FSharpVSPowerTools.Core 2.3.0
 - FSharp.Compiler.Service 2.0.0.4
 - Microsoft.Data.OData 5.7.0
 - WindowsAzure.Storage 6.2.0
 - FSharp.Core 4.0.0.1
 - Microsoft.Azure.Common 2.1.0
 - Zlib.Portable 1.11.0
 - Hyak.Common 1.1.0
 - Microsoft.Bcl 1.1.10
 - Microsoft.Bcl.Build 1.0.21
 - Microsoft.Data.Edm 5.7.0
 - System.Spatial 5.7.0
 - Microsoft.Data.Services.Client 5.7.0
 - Microsoft.Azure.Common.Dependencies 1.0.0
 - Microsoft.Azure.KeyVault.Core 1.0.0
 - Microsoft.Bcl.Async 1.0.168

Please let me know if there is something I should be doing differently.

**Comment by forki** [comment]
// @matthid

**Comment by forki** [comment]
can you try to run paket update? Does it already help?

How can we reproduce this?

**Comment by matthid** [comment]
can't really say anything without a repro or more info. I would assume (or as @tpetricek calls it: psychic debugging) you are building for net40 and added the Bcl Library, but are not copying it to the output directory.

If you can't provide a repro you can at least enable logging by setting the environment variable `FSHARP_FORMATTING_LOG` to `ALL` and then attaching the `FSharp.Formatting.svclog` here

**Comment by johnazariah** [comment]
@matthid :+1: 

I'm totally new to Project Scaffold and I've blindly followed instructions on the site page to set up a project. I'm going to try and do this again from scratch being more careful in following instructions.

I'll let you know if the problem persists.

For your reference, I was building against 4.5.1 and hadn't written any reference documentation. The build *was* working on the 20th, and suddenly started failing at that step from then. I couldn't find a correlation with any of my checkins.

Here's the AppVeyor log if that's of any help: https://ci.appveyor.com/project/johnazariah/batch-toolkit-fsharp

**Comment by johnazariah** [comment]
OK. I was able to repro:

* I re-cloned ProjectScaffold from scratch
* Ran build to set things up. Succeeded.
* Ran build again. All targets, including GenerateReferenceDocs passed.
* I put code in my src and test projects, targeted to 4.5, and ran build.
* Code compiles cleanly 
* All tests run and pass
* All targets before GenerateReferenceDocs pass
* GenerateReferenceDocs failed immediately! Attaching the svclog as requested.

[FSharp.Formatting.Logs.zip](https://github.com/fsprojects/ProjectScaffold/files/120384/FSharp.Formatting.Logs.zip)

Thanks for your help!

**Comment by matthid** [comment]
This is most likely a problem with the dependencies or the project setup. When targeting net45 `System.Threading.Tasks` from Microsoft.Bcl is not required and should not be referenced.

**Comment by johnazariah** [comment]
The problem resolved itself after I fixed up a bunch of references in my project.
