### ISSUE TITLE
Paket failing on Mono build.

### ISSUE THREAD

**Issue by jinlmsft** [fsprojects/ProjectScaffold#238]
On Linux/Mono, build the current main branch of ProjectScaffold fails with: (Network is verified to be OK). 

No version specified. Downloading latest stable.
Paket.exe 2.50.11.0 is up to date.
Paket version 2.50.11.0
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/SourceLink.Fake/SourceLink.Fake.1.1.0.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading SourceLink.Fake 1.1.0
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/SourceLink.Fake/SourceLink.Fake.1.1.0.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading SourceLink.Fake 1.1.0 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FAKE/FAKE.4.14.5.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FAKE 4.14.5
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FAKE/FAKE.4.14.5.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading FAKE 4.14.5 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Compiler.Service/FSharp.Compiler.Service.1.4.2.3.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FSharp.Compiler.Service 1.4.2.3
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Compiler.Service/FSharp.Compiler.Service.1.4.2.3.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading FSharp.Compiler.Service 1.4.2.3 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Formatting/FSharp.Formatting.2.13.2.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FSharp.Formatting 2.13.2
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Formatting/FSharp.Formatting.2.13.2.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading FSharp.Formatting 2.13.2 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FSharpVSPowerTools.Core 2.2.0
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading FSharpVSPowerTools.Core 2.2.0 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Bcl/Microsoft.Bcl.1.1.10.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading Microsoft.Bcl 1.1.10
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Bcl/Microsoft.Bcl.1.1.10.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading Microsoft.Bcl 1.1.10 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Bcl.Build/Microsoft.Bcl.Build.1.0.21.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading Microsoft.Bcl.Build 1.0.21
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Bcl.Build/Microsoft.Bcl.Build.1.0.21.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading Microsoft.Bcl.Build 1.0.21 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Net.Http/Microsoft.Net.Http.2.2.29.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading Microsoft.Net.Http 2.2.29
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Microsoft.Net.Http/Microsoft.Net.Http.2.2.29.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading Microsoft.Net.Http 2.2.29 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Octokit/Octokit.0.17.0.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading Octokit 0.17.0
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/Octokit/Octokit.0.17.0.nupkg.
Message: The requested feature is not implemented.
  ==> Trying again
Downloading Octokit 0.17.0 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FSharpVSPowerTools.Core 2.2.0
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg.
Message: The requested feature is not implemented.
  ==> Last trial
Downloading FSharpVSPowerTools.Core 2.2.0 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Formatting/FSharp.Formatting.2.13.2.nupkg. Error: The requested feature is not implemented.
Something went wrong while downloading FSharp.Formatting 2.13.2
Message: Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharp.Formatting/FSharp.Formatting.2.13.2.nupkg.
Message: The requested feature is not implemented.
  ==> Last trial
Downloading FSharp.Formatting 2.13.2 (Build)
Could not fix timestamps in /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg. Error: The requested feature is not implemented.
Paket failed with:
    Error during extraction of /home/jinl/code/tfs.jinl/ProjectScaffold/packages/build/FSharpVSPowerTools.Core/FSharpVSPowerTools.Core.2.2.0.nupkg.
Message: The requested feature is not implemented.
 In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.

**Comment by nterry** [comment]
I got this error too! It seems to fail with versions of mono somewhere between 3.8 and 3.12 (3.12 works)

**Comment by nterry** [comment]
Any ideas?

**Comment by dsyme** [comment]
Please try a later Mono, at least 4.2.0
