### ISSUE TITLE
Multiple search of Octokit directory leads to a warning

### ISSUE THREAD

**Issue by jinlmsft** [fsprojects/ProjectScaffold#239]
Current implementation of Fake\modules\Octokit gives the following search directories:

#I @"../../../../../packages/Octokit/lib/net45"
#I @"../../packages/Octokit/lib/net45"
#I @"../../../../../../packages/build/Octokit/lib/net45"

Only the first directory is valid under ProjectScaffold. The other two gives out a warning that the corresponding directory doesn't exist. The warning may confuse the developer.

**Comment by forki** [comment]
Yeah this is unfortunate, but it's currently needed.

**Comment by forki** [comment]
found a workaround
