### ISSUE TITLE
MissingMethodException in GenerateHelp with new version of FSharp.Compiler.Service

### ISSUE THREAD

**Issue by ikarni** [fsprojects/ProjectScaffold#242]
I am getting MissingMethodException in GenerateHelp target using build.cmd on clean project. I was able to track it down to FSharp.Compiler.Service library. It looks like version 2.0.0.7 broke something. If I downgrade by adding line
`nuget FSharp.Compiler.Service <= 2.0.0.6`
to Build group in paket.dependencies, it works.

**Comment by forki** [comment]
Yes. That's unfortunate.

/cc @tpetricek, @dsyme

**Comment by forki** [comment]
fixed
