### ISSUE TITLE
Some issues related to paket and FSharp.Core

### ISSUE THREAD

**Issue by simendsjo** [fsprojects/ProjectScaffold#249]
I'm not sure why this is not done, but it's things that causes me problems.
- [Referencing FSharp.Core](https://github.com/fsprojects/ProjectScaffold/blob/master/src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj#L39) directly in the fsproj files means we'll never use a newer FSharp.Core if available.
- `redirects: on` is needed in `paket.dependencies` in order to generate redirects for FSharp.Core (actually all packages, but I usually use this without any issue)
- Without `App.config`, Paket cannot add assembly redirects for FSharp.Core

Should I add some PRs for these issues, or is there a good reason why it's this way?

**Comment by forki** [comment]
Actually it should do redirects:force on the fsharp.core package. Yes please send Pull request

**Comment by dsyme** [comment]
This has been done
