### ISSUE TITLE
Add codecov.io support

### ISSUE THREAD

**Issue by jack-pappas** [fsprojects/ProjectScaffold#259]
### Description

Implement support for codecov.io (free service for collecting test coverage results).
### Related information

codecov.io is a free service that integrates with Github, and it provides a way to collect test coverage results and publish it to their service; this gives you a 'badge' you can add to the repository's README to make it easy to see how well a library's code is covered by it's test suite.

An example integration for a C# project can be found at:
https://github.com/codecov/example-csharp

**Comment by dsyme** [comment]
Closing old suggestions (please send a PR if you want it)

**Comment by dsyme** [comment]
This was a great suggestion, my apologies for closing it.

**Comment by jackfoxy** [comment]
Even if the maintainers do not want this, I would merge it into my fork.
