### ISSUE TITLE
Discussion: Use Expecto for test project

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/ProjectScaffold#305]
I guess everyone knows my opinion about "traditional" .Net test frameworks, and noticed that I'm big fan of Expecto. ;)

But there are some real advantages:
1. Promoting community based solution 
2. Promoting "idiomatic" F# way
3. Removing problems with Assembly Redirects that everyone has with test frameworks using external runners

**Comment by jackfoxy** [comment]
Already did this in my fork

**Comment by jackfoxy** [comment]
Now covered by https://github.com/fsprojects/ProjectScaffold/issues/325
