### ISSUE TITLE
Proposed updates to ProjectScaffold

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/ProjectScaffold#325]
## Proposed updates to ProjectScaffold

I have some changes in my personal fork I can submit to the master branch here. I'll propose a thumbs up/down vote on each.

I have no experience with dotnet templates, and so no opinion about whether this project is suitable to convert, or if any of my changes are compatible.

1) Dotnet SDK projects. 
I multi-target the main library project to net45;net47;netstandard2.0.
And I have added a console project I multi-target to net47;netcoreapp2.0
Test project is targeted to net47

2) Drop NUnit and make the test project Expecto tests.
Includes some simple/random FsCheck generators, (maybe not the best examples in the world.)
(Ideally making NUnit or Expecto an option in the initialization would be nice, but that's more work than I am interested in doing.)

3) Additional console app using Argu lib.
I also stubbed-out the common way I parse commands using Argu. In truth I threw together this generalized parsing in a hurry from some existing projects, so I don't guarantee all the parsing works perfectly out of the box, but it is close.

4) All solution files accessible from within solution IDE.
Why open the solution in VS IDE and not have access to files like .gitignore, appveyor.yml, build.cmd, etc?

5) Latest FSharp.Formatting prerelease. 
If you haven't noticed, the release version of FSharp.Formatting has lots of problems.

6) My personalized prelude file in the library project.
https://github.com/jackfoxy/ProjectScaffold/blob/master/src/FSharp.ProjectTemplate/Prelude.fs

**Comment by jackfoxy** [comment]
## Dotnet SDK projects
thumbs up/down

**Comment by jackfoxy** [comment]
## Drop NUnit and make the test project Expecto tests
thumbs up/down

**Comment by jackfoxy** [comment]
## Additional console app using Argu lib
thumbs up/down

**Comment by jackfoxy** [comment]
## All solution files accessible from within solution IDE
thumbs up/down

**Comment by jackfoxy** [comment]
## Latest FSharp.Formatting prerelease
thumbs up/down

**Comment by jackfoxy** [comment]
## My personalized prelude file in the library project
thumbs up/down

**Comment by Krzysztof-Cieslak** [comment]
If we went with SDK template road some of those decisions may be done by users, with parameters. In particular it would make sense for those ideas (from above list) - additional console app, type of test framework, custom prelude

**Comment by jackfoxy** [comment]
If someone wants to do the work to turn this project into a SDK template, I would accept the PR.

**Comment by jackfoxy** [comment]
I'm curious to hear the reason(s) for down-voting making all files available from within the solution?

**Comment by jackfoxy** [comment]
Here's what seems to be trending favorably. I'll try to get this in on the weekend, if the trends hold.

Dotnet SDK projects

Drop NUnit and make the test project Expecto tests

Additional console app using Argu lib

All solution files accessible from within solution IDE

Latest FSharp.Formatting prerelease

**Comment by jackfoxy** [comment]
I have pushed a beta branch https://github.com/fsprojects/ProjectScaffold/tree/betanetstandard for community testing with the following changes:

**Dotnet SDK projects**
**Drop NUnit and make the test project Expecto tests**
**Additional console app using Argu lib**
**All solution files accessible from within solution IDE**
**Latest FSharp.Formatting prerelease**

I also made a couple of changes to paket.dependencies:

- eliminate separate paket groups
    I have found groups problematic in the past. The scaffold project is simple enough that it does not require groups, IMO. If anyone wants to submit a PR putting groups back in, I would accept it.

- paket framework autodetect
    I believe this is the best default option for most projects.

**Comment by jackfoxy** [comment]
I will merge early in the workweek, pending feedback.

**Comment by matthid** [comment]
@jackfoxy I guess we should update fake as well to 5

**Comment by jackfoxy** [comment]
@matthid yes, that and dotnet cli template are good next steps
I will open an issue for fake 5

**Comment by jackfoxy** [comment]
PR merged https://github.com/fsprojects/ProjectScaffold/pull/326
