### ISSUE TITLE
FAKE 5.0 implementation of build

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/ProjectScaffold#327]
### Description

FAKE 5.0 implementation of build

**Comment by jackfoxy** [comment]
This should probably be implemented as an initialization time choice between 5.0 and legacy build scripts. This would likely also impact paket.dependencies

**Comment by jackfoxy** [comment]
More important than ever, now that FAKE 5.0 released

**Comment by jackfoxy** [comment]
F# Scaffolding is not yet compatible with FAKE 5.0
https://github.com/fsprojects/FSharp.Formatting/issues/471

**Comment by matthid** [comment]
It is, look at fake itself for example

**Comment by jackfoxy** [comment]
OK, so one needs to put fake and formatting in different paket groups.

**Comment by jackfoxy** [comment]
A mostly complete implementation of FAKE 5.0 build is available on the fake5 branch.

https://github.com/fsprojects/ProjectScaffold/blob/fake5/build.template

It still needs a little bit of work in a couple areas I do not personally use. 

Please submit PRs to the fake5 branch.

1) build.sh needs updating. This should be a small task for anyone experienced in using *nix builds.
2) "GenerateDocsDebug" target is not fully wired-up. I never used this target, so I'm not the one to complete it.
3) "Release" target is untested. I never used this target.
4) "PublishNuget" target is untested...I'm old school and always manually push to Nuget.org
5) I did a minor re-orginization of the doc related targets, resulting in some target renaming. If anyone wants to submit a PR implementing the previous target names I would merge it.
6) This is untested on Appveyor and Travis CIs.

cc: @matthid

**Comment by wallymathieu** [comment]
Sweet! 👍
