### ISSUE TITLE
clone/build does not work on Mac

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/ProjectScaffold#332]
### Description

clone/build does not work on Mac

### Repro steps

from twitter report, needs more info

**Comment by jackfoxy** [comment]
Some information I picked up might be relevant: 
 
To use dotnet build on non-windows for non-netstandard/netcoreapp frameworks you need to supply the path to the mono BCL libraries like so: 
export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

Here's an example you may like: https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/netfx.props
You can copy this file and include it in your fsprojs to get the same effect

**Comment by jackfoxy** [comment]
@jeremyabbott  I got this feedback over twitter 
I get  build failures on /usr/local/share/dotnet/sdk/2.1.301/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7" were not found.

Perhaps we should rollback the mutitargetting to net461?
https://twitter.com/paytonrules/status/1022321025135112192

**Comment by jeremyabbott** [comment]
I’ll take a look ASAP.

-- 
Jeremy Abbott

**Comment by jackfoxy** [comment]
I'm declaring this fixed. If any other Mac issues arise we can open a new issue.
