### ISSUE TITLE
This should be the default for any .NET project

### ISSUE THREAD

**Issue by forki** [fsprojects/ProjectScaffold#42]
Hi,

this setup is useful enough to be used in all .NET projects not only F# projects.
We use nearly the same setup for https://github.com/octokit/octokit.net
We should add a C# project and remove all F# naming.

Cheers,
Steffen

**Comment by Vidarls** [comment]
#102 is now merged, and as such ProjectScaffold supports C# projects. We're using it for more C# projects than F# projects now :smile:

**Comment by forki** [comment]
@Vidarls my sincerest condolences for having so many C# projects


Joking aside, thanks for helping us to make this ecosystem great. Your work on all these projects is super cool. :heart:

**Comment by Vidarls** [comment]
Don't be sorry, adding Scaffold, Format and Fake, makes every project an F# project :stuck_out_tongue_winking_eye:

**Comment by DamianReeves** [comment]
In the spirit of this thread, it would be great if as part of the options in the init.fsx script if we allowed the user to decide if the default project should be an C# project instead of F#.
