### ISSUE TITLE
Missing method exception in copyFiles

### ISSUE THREAD

**Issue by evelinag** [fsprojects/ProjectScaffold#53]
In generate.fsx, copyFiles() throws the following exception in F# interactive:

```
System.MissingMethodException: Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2<Boolean,Microsoft.FSharp.Collections.FSharpList`1<System.String>> Fake.FileHelper.CopyRecursive(System.String, System.String)'.
   at FSI_0047.copyFiles()
   at <StartupCode$FSI_0048>.$FSI_0048.main@()
```

It works when it's called from the command line though. 
I'm using Visual Studio 2012 (I don't have VS 2013 installed).

**Comment by lefthandedgoat** [comment]
I had the same issue recently with newer version so Fake.  Installing the Visual F# Tools 4.0 fixed it.
