### ISSUE TITLE
Add target(s) for viewing API docs and help files locally  

### ISSUE THREAD

**Issue by pblasucci** [fsprojects/ProjectScaffold#96]
Basically, copying existing tasks and change the `--define:RELEASE` flag to be `--define:DEBUG`. 

Maybe call the new tasks "Preview___" instead of "Generate___"?

**Comment by aureole82** [comment]
Sorry guys, I don't get it.

@pblasucci Somebody implemented the task `GenerateHelpDebug`. So calling `> build GenerateHelpDebug` does the job. But is it possible to set a switch which calls `GenerateHelpDebug` on `>build.cmd` and `GenerateHelp` on `>release.cmd`?


But that doesn't work
 would appreciate if your solution could be implemented. Especially as I fail all the time.

@forki Sorry, I can't find the solution on your [page](http://fsprojects.github.io/ProjectScaffold/writing-docs.html).
